#ifndef QXTGLOBALSHORTCUT_GLOBAL_H
#define QXTGLOBALSHORTCUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QXTGLOBALSHORTCUT_LIBRARY)
#  define QXTGLOBALSHORTCUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QXTGLOBALSHORTCUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QXTGLOBALSHORTCUT_GLOBAL_H
