#ifndef OESCREENSHOT_GLOBAL_H
#define OESCREENSHOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OESCREENSHOT_LIBRARY)
#  define OESCREENSHOTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OESCREENSHOTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OESCREENSHOT_GLOBAL_H
